### ISSUE TITLE
水印字体设置颜色有偏差

### ISSUE THREAD

**Issue by zhguo** [saucxs/watermark#1]
用这个插件设置的字体颜色值有偏差，颜色很浅，是什么原因？

**Comment by saucxs** [comment]
是因为设置了水印透明度，在正常的字体颜色的基础上增加了 alpha透明度。

**Comment by angus006** [comment]
截图文件存储成为jpg，或者照相存成jpg格式的就无法还原显示水印，是何原因？

**Comment by saucxs** [comment]
保存为jpg或者其他格式的，水印是可以显示的，不知道你说的具体是什么情况下出现的，如果水印的透明度调的很低，可以使用PS让水印显现。 @angus006

**Comment by yunhai0920** [comment]
demo http://www.chengxinsong.cn/watermark_test/ 已经无法测试了 是关闭了吗？

**Comment by saucxs** [comment]
这个目前正在更改，可以先访问这个http://suning.chengxinsong.cn/，看到效果 @yunhai0920

**Comment by saucxs** [comment]
现在readme已经修改，目前统一现在[](http://blog.mwcxs.top/static/testTool/index.html)访问这个

**Comment by saucxs** [comment]
png是无损数据格式压缩的，JPG是有损数据格式压缩的，造成了ps无法还原jpg格式的暗水印
