### ISSUE TITLE
360急速浏览器无法显示水印

### ISSUE THREAD

**Issue by zeenoxie** [saucxs/watermark#2]
IE11和Chrome63都正常的。

**Comment by saucxs** [comment]
目前支持：Chrome,FireFox,IE11。

**Comment by saucxs** [comment]
但是自己亲测了一下，360浏览器的急速模式，可以正常显示。






￼

**Comment by zeenoxie** [comment]
用IE11可以，用360不可以，会不会是网页有其他干扰代码？

[版本图](http://i2.bvimg.com/628581/9ceb96dae891cdb9.jpg)
[效果图](http://i2.bvimg.com/628581/2355646f88505a83.jpg)

**Comment by saucxs** [comment]
360极速浏览器记录上次 使用的模式，例如 你上次是极速，他下次也是极速，是webkit内核。如果上次是兼容，下次就默认兼容，是电脑中IE内核。在页面开发中可以指定360极速浏览器的模式，加入
<meta name="renderer" content="webkit"> 
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
