### ISSUE TITLE
水印组件能销毁么

### ISSUE THREAD

**Issue by tjsome** [saucxs/watermark#8]
水印组件能销毁么

**Comment by saucxs** [comment]
可以销毁

**Comment by zhengxiaodong502** [comment]
请问我登录页面不要水印，其他页面要，但退出来了，登录页面又有水印，如何销毁呢

**Comment by saucxs** [comment]
水印在销毁的时候，你可以采用根据路由判断是否是登陆页，或者根据页面上是否含有watermark的id元素，来判断来销毁组件
